#!/bin/bash
g++ std=c++11 ~/dev/LLH/llh.cpp

read -p "Input URL or existing LLH: " userin
./a.out $userin > out.txt
cat out.txt | pbcopy
echo -ne "\n'$userin' --> "
cat out.txt
echo "Value copied to clipboard."
